[pytest]
filterwarnings =
    ignore:Trying to unpickle estimator .* when using version .*:sklearn.exceptions.InconsistentVersionWarning
markers =
    integration: Marks integration tests that involve multiple components or external APIs.
