/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#480015',
        background: '#0e0e0e',
        'on-surface-variant': '#acabaa',
        'error-dim': '#bb5551',
        'tertiary-fixed-dim': '#e02057',
        secondary: '#00FFC2',
        'on-secondary-fixed': '#004935',
        'on-primary-container': '#d0d0d0',
        'secondary-container': '#004432',
        'inverse-on-surface': '#565555',
        'on-secondary': '#005c44',
        outline: '#767575',
        'surface-variant': '#252626',
        'outline-variant': '#484848',
        'secondary-fixed': '#36ffc4',
        'on-error': '#490106',
        'surface-bright': '#2c2c2c',
        'on-background': '#e7e5e4',
        'on-primary-fixed': '#3e4040',
        'surface-container': '#191a1a',
        'on-tertiary-fixed-variant': '#fffbff',
        'on-secondary-fixed-variant': '#00694e',
        'inverse-primary': '#5e5f60',
        error: '#ee7d77',
        'tertiary-dim': '#e02057',
        'surface-container-highest': '#252626',
        'on-tertiary-container': '#000000',
        'surface-container-lowest': '#000000',
        'primary-container': '#454747',
        primary: '#c6c6c7',
        'secondary-dim': '#00edb4',
        tertiary: '#ff6e86',
        'secondary-fixed-dim': '#00f0b7',
        'primary-fixed': '#e2e2e2',
        'on-primary-fixed-variant': '#5a5c5c',
        'surface-tint': '#c6c6c7',
        'on-tertiary-fixed': '#ffffff',
        'on-error-container': '#ff9993',
        'error-container': '#7f2927',
        'on-surface': '#e7e5e4',
        surface: '#0e0e0e',
        'surface-container-high': '#1f2020',
        'tertiary-fixed': '#f23063',
        'primary-fixed-dim': '#d4d4d4',
        'inverse-surface': '#fcf9f8',
        'surface-dim': '#0e0e0e',
        'primary-dim': '#b8b9b9',
        'tertiary-container': '#f23063',
        'on-secondary-container': '#00d9a4',
        'on-primary': '#3f4041',
        'surface-container-low': '#131313',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
